# Generated by Django 5.2.17 on 2026-09-01 20:53

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("business", "0003_business_brand_fields"),
        ("customer", "0001_initial"),
        ("sales", "0005_saleline_applied_cost_price"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Receivable",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("invoice_number", models.CharField(max_length=100)),
                (
                    "original_amount",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                (
                    "paid_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "outstanding_amount",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("UNPAID", "Unpaid"),
                            ("PARTIAL", "Partial"),
                            ("PAID", "Paid"),
                            ("VOIDED", "Voided"),
                            ("CLOSED", "Closed"),
                        ],
                        default="UNPAID",
                        max_length=20,
                    ),
                ),
                ("due_date", models.DateField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "business",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="receivables",
                        to="business.business",
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="receivables",
                        to="customer.customer",
                    ),
                ),
                (
                    "location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="receivables",
                        to="business.location",
                    ),
                ),
                (
                    "sale",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="receivable",
                        to="sales.sale",
                    ),
                ),
            ],
            options={
                "verbose_name": "Receivable",
                "verbose_name_plural": "Receivables",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PaymentAllocation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "payment_method",
                    models.CharField(
                        choices=[
                            ("CASH", "Cash"),
                            ("QRIS", "QRIS"),
                            ("TRANSFER", "Transfer"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "payment_date",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("reference", models.CharField(blank=True, max_length=100)),
                ("notes", models.TextField(blank=True)),
                ("is_reversed", models.BooleanField(default=False)),
                ("reversed_at", models.DateTimeField(blank=True, null=True)),
                ("reversal_reason", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "business",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payment_allocations",
                        to="business.business",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_payments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "reversed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reversed_payments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "receivable",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="allocations",
                        to="receivable.receivable",
                    ),
                ),
            ],
            options={
                "verbose_name": "Payment Allocation",
                "verbose_name_plural": "Payment Allocations",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="receivable",
            index=models.Index(
                fields=["business"], name="receivable__busines_2f0899_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="receivable",
            index=models.Index(
                fields=["location"], name="receivable__locatio_2d8806_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="receivable",
            index=models.Index(
                fields=["customer"], name="receivable__custome_4022bd_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="receivable",
            index=models.Index(fields=["status"], name="receivable__status_048c0c_idx"),
        ),
        migrations.AddIndex(
            model_name="receivable",
            index=models.Index(
                fields=["due_date"], name="receivable__due_dat_d9a5e7_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="receivable",
            constraint=models.UniqueConstraint(
                fields=("business", "invoice_number"),
                name="unique_invoice_per_business",
            ),
        ),
        migrations.AddIndex(
            model_name="paymentallocation",
            index=models.Index(
                fields=["business"], name="receivable__busines_b931c7_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="paymentallocation",
            index=models.Index(
                fields=["receivable"], name="receivable__receiva_ca02cd_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="paymentallocation",
            index=models.Index(
                fields=["is_reversed"], name="receivable__is_reve_dce7a0_idx"
            ),
        ),
    ]
