# Generated by Django 5.2.17 on 2026-08-22 12:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customer", "0001_initial"),
        ("product", "0002_variant_create"),
        ("promotion_loyalty", "0001_initial"),
        ("sales", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="sale",
            name="customer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="sales",
                to="customer.customer",
            ),
        ),
        migrations.AddField(
            model_name="sale",
            name="loyalty_earned",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name="saleline",
            name="applied_discount_type",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="saleline",
            name="applied_discount_value",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=12, null=True
            ),
        ),
        migrations.AddField(
            model_name="saleline",
            name="applied_promotion",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="sale_lines",
                to="promotion_loyalty.promotion",
            ),
        ),
        migrations.AddIndex(
            model_name="saleline",
            index=models.Index(
                fields=["applied_promotion"], name="sales_salel_applied_097da1_idx"
            ),
        ),
    ]
