# Generated by Django 5.2.17 on 2026-08-28 09:07

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("business", "0005_businessmembership_role"),
        ("sales", "0002_sale_customer_sale_loyalty_earned_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="sale",
            name="payment_method",
            field=models.CharField(
                blank=True,
                choices=[("CASH", "Cash"), ("QRIS", "QRIS"), ("TRANSFER", "Transfer")],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="sale",
            name="status",
            field=models.CharField(
                choices=[
                    ("DRAFT", "Draft"),
                    ("COMPLETED", "Completed"),
                    ("VOIDED", "Voided"),
                    ("HELD", "Held"),
                ],
                default="DRAFT",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="CashierShift",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("modal_awal", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "uang_tunai_aktual",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "selisih_kas",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("OPEN", "Open"), ("CLOSED", "Closed")],
                        default="OPEN",
                        max_length=20,
                    ),
                ),
                ("opened_at", models.DateTimeField(auto_now_add=True)),
                ("closed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "business",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shifts",
                        to="business.business",
                    ),
                ),
                (
                    "cashier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shifts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shifts",
                        to="business.location",
                    ),
                ),
            ],
            options={
                "verbose_name": "Cashier Shift",
                "verbose_name_plural": "Cashier Shifts",
                "ordering": ["-opened_at"],
            },
        ),
        migrations.AddField(
            model_name="sale",
            name="shift",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="sales",
                to="sales.cashiershift",
            ),
        ),
        migrations.AddIndex(
            model_name="cashiershift",
            index=models.Index(
                fields=["business"], name="sales_cashi_busines_db9d05_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="cashiershift",
            index=models.Index(
                fields=["location"], name="sales_cashi_locatio_4163cf_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="cashiershift",
            index=models.Index(
                fields=["cashier"], name="sales_cashi_cashier_1e4040_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="cashiershift",
            index=models.Index(fields=["status"], name="sales_cashi_status_f8ff82_idx"),
        ),
    ]
