# Generated by Django 5.2.17 on 2026-08-28 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0003_sale_payment_method_alter_sale_status_cashiershift_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sale",
            name="status",
            field=models.CharField(
                choices=[
                    ("DRAFT", "Draft"),
                    ("COMPLETED", "Completed"),
                    ("VOIDED", "Voided"),
                ],
                default="DRAFT",
                max_length=20,
            ),
        ),
    ]
