# Generated by Django 5.2.17 on 2026-09-01 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0004_alter_sale_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="saleline",
            name="applied_cost_price",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=12, null=True
            ),
        ),
    ]
