# Generated by Django 5.2.17 on 2026-08-21 18:21

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0001_product_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Variant",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="variants",
                        to="product.product",
                    ),
                ),
            ],
            options={
                "verbose_name": "Variant",
                "verbose_name_plural": "Variants",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["product", "name"],
                        name="product_var_product_13df26_idx",
                    )
                ],
            },
        ),
    ]
