# Generated by Django 5.2.17 on 2026-09-01 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0002_variant_create"),
    ]

    operations = [
        migrations.AddField(
            model_name="variant",
            name="cost_price",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
