# Generated by Django 5.2.17 on 2026-08-30 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0002_create_basic_plan"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="purpose",
            field=models.CharField(
                choices=[
                    ("INITIAL", "Initial"),
                    ("RENEWAL", "Renewal"),
                    ("UPGRADE", "Upgrade"),
                ],
                default="INITIAL",
                max_length=20,
            ),
        ),
    ]
