# Generated by Django 5.2.17 on 2026-08-22 12:13

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("business", "0004_businessmembership"),
        ("customer", "0001_initial"),
        ("product", "0002_variant_create"),
    ]

    operations = [
        migrations.CreateModel(
            name="LoyaltyProgram",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "status",
                    models.CharField(
                        choices=[("ACTIVE", "Active"), ("INACTIVE", "Inactive")],
                        default="ACTIVE",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "business",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="loyalty_programs",
                        to="business.business",
                    ),
                ),
            ],
            options={
                "verbose_name": "Loyalty Program",
                "verbose_name_plural": "Loyalty Programs",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="CustomerLoyaltyRecord",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "points_balance",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="loyalty_records",
                        to="customer.customer",
                    ),
                ),
                (
                    "program",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="records",
                        to="promotion_loyalty.loyaltyprogram",
                    ),
                ),
            ],
            options={
                "verbose_name": "Customer Loyalty Record",
                "verbose_name_plural": "Customer Loyalty Records",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Promotion",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "discount_type",
                    models.CharField(
                        choices=[("PERCENTAGE", "Percentage"), ("FIXED", "Fixed")],
                        max_length=20,
                    ),
                ),
                (
                    "discount_value",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                ("valid_from", models.DateTimeField()),
                ("valid_to", models.DateTimeField()),
                (
                    "status",
                    models.CharField(
                        choices=[("ACTIVE", "Active"), ("INACTIVE", "Inactive")],
                        default="ACTIVE",
                        max_length=20,
                    ),
                ),
                (
                    "applicability",
                    models.CharField(
                        choices=[
                            ("BUSINESS_WIDE", "Business-wide"),
                            ("PRODUCT_VARIANT", "Product/Variant targeted"),
                        ],
                        default="BUSINESS_WIDE",
                        max_length=30,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "business",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="promotions",
                        to="business.business",
                    ),
                ),
                (
                    "target_product",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="promotions",
                        to="product.product",
                    ),
                ),
                (
                    "target_variant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="promotions",
                        to="product.variant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Promotion",
                "verbose_name_plural": "Promotions",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="loyaltyprogram",
            index=models.Index(
                fields=["business"], name="promotion_l_busines_f01409_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="loyaltyprogram",
            index=models.Index(fields=["status"], name="promotion_l_status_aa0dd7_idx"),
        ),
        migrations.AddIndex(
            model_name="customerloyaltyrecord",
            index=models.Index(
                fields=["program", "customer"], name="promotion_l_program_6f28bb_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="customerloyaltyrecord",
            constraint=models.UniqueConstraint(
                fields=("program", "customer"),
                name="unique_program_customer_loyalty_record",
            ),
        ),
        migrations.AddIndex(
            model_name="promotion",
            index=models.Index(
                fields=["business"], name="promotion_l_busines_3a0b4c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="promotion",
            index=models.Index(
                fields=["status", "applicability"], name="promotion_l_status_ea8114_idx"
            ),
        ),
    ]
