# Generated by Django 5.2.17 on 2026-08-27 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("business", "0004_businessmembership"),
    ]

    operations = [
        migrations.AddField(
            model_name="businessmembership",
            name="role",
            field=models.CharField(
                choices=[("OWNER", "Owner"), ("ADMIN", "Admin"), ("KASIR", "Kasir")],
                default="KASIR",
                max_length=20,
            ),
        ),
    ]
