# Generated by Django 5.2.17 on 2026-08-30 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("business", "0005_businessmembership_role"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="subscription",
            name="unique_active_subscription_per_business",
        ),
        migrations.AlterField(
            model_name="subscription",
            name="status",
            field=models.CharField(
                choices=[
                    ("TRIAL", "Trial"),
                    ("ONBOARDING", "Onboarding"),
                    ("ACTIVE", "Active"),
                    ("SUSPENDED", "Suspended"),
                    ("CANCELED", "Canceled"),
                ],
                default="TRIAL",
                max_length=20,
            ),
        ),
        migrations.AddConstraint(
            model_name="subscription",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status__in", ["TRIAL", "ONBOARDING", "ACTIVE"])),
                fields=("business",),
                name="unique_active_subscription_per_business",
            ),
        ),
    ]
