# Generated by Django 5.2.17 on 2026-08-30 19:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0003_payment_purpose"),
        (
            "business",
            "0006_remove_subscription_unique_active_subscription_per_business_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="subscription",
            name="period_end",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="subscription",
            name="period_start",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="subscription",
            name="plan",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="billing.plan",
            ),
        ),
    ]
