# Generated by Django 5.2.17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("business", "0007_subscription_period_end_subscription_period_start_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subscription",
            name="status",
            field=models.CharField(
                choices=[
                    ("TRIAL", "Trial"),
                    ("ONBOARDING", "Onboarding"),
                    ("ACTIVE", "Active"),
                    ("SUSPENDED", "Suspended"),
                    ("EXPIRED", "Expired"),
                    ("CANCELED", "Canceled"),
                ],
                default="TRIAL",
                max_length=20,
            ),
        ),
    ]
