# Generated by Django 5.2.17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("business", "0008_subscription_status_expired"),
    ]

    operations = [
        migrations.AddField(
            model_name="business",
            name="business_type",
            field=models.CharField(blank=True, default="Usaha Lainnya", max_length=100),
        ),
    ]
