from django.urls import path

from apps.admin.views import (
    AdminAccountListView,
    AdminAccountDetailView,
    AdminOwnerListView,
    AdminOwnerDetailView,
    AdminBusinessListView,
    AdminBusinessDetailView,
    AdminUserListView,
    AdminUserDetailView,
    AdminAdminListView,
    AdminAdminDetailView,
    AdminSubscriptionListView,
    AdminSubscriptionDetailView,
    AdminPlanListCreateView,
    AdminPlanDetailUpdateView,
    AdminPlanEnableView,
    AdminPlanDisableView,
    AdminPaymentListView,
    AdminPaymentDetailView,
    AdminBillingSummaryView,
    AdminDashboardView,
    AdminModuleListView,
    AdminModuleDetailView,
    AdminModuleEnableView,
    AdminModuleDisableView,
    AdminFeatureListView,
    AdminFeatureDetailView,
    AdminFeatureEnableView,
    AdminFeatureDisableView,
    AdminPlanFeatureListView,
    AdminPlanFeatureDeleteView,
    AdminBusinessFeatureListView,
    AdminSupportTicketListView,
    AdminSupportTicketDetailView,
    AdminSupportTicketReplyView,
)

app_name = "koperaadmin"

urlpatterns = [
    path("dashboard/", AdminDashboardView.as_view(), name="dashboard"),
    path("accounts/", AdminAccountListView.as_view(), name="account-list"),
    path(
        "accounts/<uuid:owner_user_id>/",
        AdminAccountDetailView.as_view(),
        name="account-detail",
    ),
    path("owners/", AdminOwnerListView.as_view(), name="owner-list"),
    path(
        "owners/<uuid:owner_id>/",
        AdminOwnerDetailView.as_view(),
        name="owner-detail",
    ),
    path("businesses/", AdminBusinessListView.as_view(), name="business-list"),
    path(
        "businesses/<uuid:business_id>/",
        AdminBusinessDetailView.as_view(),
        name="business-detail",
    ),
    path("users/", AdminUserListView.as_view(), name="user-list"),
    path(
        "users/<uuid:user_id>/",
        AdminUserDetailView.as_view(),
        name="user-detail",
    ),
    path("admins/", AdminAdminListView.as_view(), name="admin-list"),
    path(
        "admins/<uuid:admin_id>/",
        AdminAdminDetailView.as_view(),
        name="admin-detail",
    ),
    path("subscriptions/", AdminSubscriptionListView.as_view(), name="subscription-list"),
    path(
        "subscriptions/<uuid:subscription_id>/",
        AdminSubscriptionDetailView.as_view(),
        name="subscription-detail",
    ),
    path("plans/", AdminPlanListCreateView.as_view(), name="plan-list-create"),
    path(
        "plans/<uuid:plan_id>/",
        AdminPlanDetailUpdateView.as_view(),
        name="plan-detail-update",
    ),
    path(
        "plans/<uuid:plan_id>/enable/",
        AdminPlanEnableView.as_view(),
        name="plan-enable",
    ),
    path(
        "plans/<uuid:plan_id>/disable/",
        AdminPlanDisableView.as_view(),
        name="plan-disable",
    ),
    path("payments/", AdminPaymentListView.as_view(), name="payment-list"),
    path(
        "payments/<uuid:payment_id>/",
        AdminPaymentDetailView.as_view(),
        name="payment-detail",
    ),
    path("billing/summary/", AdminBillingSummaryView.as_view(), name="billing-summary"),
    path("modules/", AdminModuleListView.as_view(), name="module-list"),
    path("modules/<uuid:module_id>/", AdminModuleDetailView.as_view(), name="module-detail"),
    path(
        "modules/<uuid:module_id>/enable/",
        AdminModuleEnableView.as_view(),
        name="module-enable",
    ),
    path(
        "modules/<uuid:module_id>/disable/",
        AdminModuleDisableView.as_view(),
        name="module-disable",
    ),
    path("features/", AdminFeatureListView.as_view(), name="feature-list"),
    path("features/<uuid:feature_id>/", AdminFeatureDetailView.as_view(), name="feature-detail"),
    path(
        "features/<uuid:feature_id>/enable/",
        AdminFeatureEnableView.as_view(),
        name="feature-enable",
    ),
    path(
        "features/<uuid:feature_id>/disable/",
        AdminFeatureDisableView.as_view(),
        name="feature-disable",
    ),
    path(
        "plans/<uuid:plan_id>/features/",
        AdminPlanFeatureListView.as_view(),
        name="plan-feature-list",
    ),
    path(
        "plans/<uuid:plan_id>/features/<uuid:feature_id>/",
        AdminPlanFeatureDeleteView.as_view(),
        name="plan-feature-delete",
    ),
    path(
        "businesses/<uuid:business_id>/features/",
        AdminBusinessFeatureListView.as_view(),
        name="business-feature-list",
    ),
    path(
        "businesses/<uuid:business_id>/features/<uuid:feature_id>/",
        AdminBusinessFeatureListView.as_view(),
        name="business-feature-update",
    ),
    path("support/tickets/", AdminSupportTicketListView.as_view(), name="support-ticket-list"),
    path(
        "support/tickets/<uuid:ticket_id>/",
        AdminSupportTicketDetailView.as_view(),
        name="support-ticket-detail",
    ),
    path(
        "support/tickets/<uuid:ticket_id>/replies/",
        AdminSupportTicketReplyView.as_view(),
        name="support-ticket-replies",
    ),
]
