# Generated by Django 5.2.17 on 2026-09-02 09:23

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("business", "0003_business_brand_fields"),
        ("purchasing", "0001_initial"),
        ("supplier", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Payable",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("invoice_number", models.CharField(max_length=100)),
                (
                    "original_amount",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                (
                    "paid_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "outstanding_amount",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("UNPAID", "Unpaid"),
                            ("PARTIAL", "Partial"),
                            ("PAID", "Paid"),
                            ("VOIDED", "Voided"),
                            ("CLOSED", "Closed"),
                        ],
                        default="UNPAID",
                        max_length=20,
                    ),
                ),
                ("due_date", models.DateField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "business",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payables",
                        to="business.business",
                    ),
                ),
                (
                    "location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="payables",
                        to="business.location",
                    ),
                ),
                (
                    "purchase_order",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="payable",
                        to="purchasing.purchaseorder",
                    ),
                ),
                (
                    "supplier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="payables",
                        to="supplier.supplier",
                    ),
                ),
            ],
            options={
                "verbose_name": "Payable",
                "verbose_name_plural": "Payables",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SupplierPaymentAllocation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "payment_method",
                    models.CharField(
                        choices=[
                            ("CASH", "Cash"),
                            ("QRIS", "QRIS"),
                            ("TRANSFER", "Transfer"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "payment_date",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("reference", models.CharField(blank=True, max_length=100)),
                ("notes", models.TextField(blank=True)),
                ("is_reversed", models.BooleanField(default=False)),
                ("reversed_at", models.DateTimeField(blank=True, null=True)),
                ("reversal_reason", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "business",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="supplier_payment_allocations",
                        to="business.business",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_supplier_payments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "payable",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="allocations",
                        to="payable.payable",
                    ),
                ),
                (
                    "reversed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reversed_supplier_payments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Supplier Payment Allocation",
                "verbose_name_plural": "Supplier Payment Allocations",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="payable",
            index=models.Index(
                fields=["business"], name="payable_pay_busines_cdb038_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="payable",
            index=models.Index(
                fields=["location"], name="payable_pay_locatio_73cbf7_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="payable",
            index=models.Index(
                fields=["supplier"], name="payable_pay_supplie_4d5920_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="payable",
            index=models.Index(fields=["status"], name="payable_pay_status_115259_idx"),
        ),
        migrations.AddIndex(
            model_name="payable",
            index=models.Index(
                fields=["due_date"], name="payable_pay_due_dat_c53d1c_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="payable",
            constraint=models.UniqueConstraint(
                fields=("business", "invoice_number"),
                name="unique_payable_invoice_per_business",
            ),
        ),
        migrations.AddIndex(
            model_name="supplierpaymentallocation",
            index=models.Index(
                fields=["business"], name="payable_sup_busines_6914a1_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="supplierpaymentallocation",
            index=models.Index(
                fields=["payable"], name="payable_sup_payable_0cb9a1_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="supplierpaymentallocation",
            index=models.Index(
                fields=["is_reversed"], name="payable_sup_is_reve_c71a7d_idx"
            ),
        ),
    ]
