# Generated by Django 5.2.17 on 2026-08-21 20:24

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("business", "0004_businessmembership"),
        ("product", "0002_variant_create"),
    ]

    operations = [
        migrations.CreateModel(
            name="Stock",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("quantity", models.DecimalField(decimal_places=2, max_digits=12)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stocks",
                        to="business.location",
                    ),
                ),
                (
                    "variant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stocks",
                        to="product.variant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Stock",
                "verbose_name_plural": "Stocks",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["location"], name="inventory_s_locatio_bb95d2_idx"
                    ),
                    models.Index(
                        fields=["variant"], name="inventory_s_variant_860ca8_idx"
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("variant", "location"),
                        name="unique_stock_per_variant_location",
                    )
                ],
            },
        ),
    ]
