# Generated by Django 5.2.17 on 2026-08-22 08:43

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("business", "0004_businessmembership"),
        ("inventory", "0001_initial"),
        ("product", "0002_variant_create"),
    ]

    operations = [
        migrations.CreateModel(
            name="Batch",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("code", models.CharField(max_length=255)),
                ("quantity", models.DecimalField(decimal_places=2, max_digits=12)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="batches",
                        to="business.location",
                    ),
                ),
                (
                    "variant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="batches",
                        to="product.variant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Batch",
                "verbose_name_plural": "Batches",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["location"], name="inventory_b_locatio_b279ec_idx"
                    ),
                    models.Index(
                        fields=["variant"], name="inventory_b_variant_cfd7fd_idx"
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("location", "code"),
                        name="unique_batch_per_location_code",
                    )
                ],
            },
        ),
    ]
