# Generated by Django 5.2.17 on 2026-08-22 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0002_batch"),
    ]

    operations = [
        migrations.AddField(
            model_name="batch",
            name="expired_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
