# Generated by Django 5.2.17 on 2026-08-22 08:53

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0003_batch_expired_date"),
    ]

    operations = [
        migrations.CreateModel(
            name="SerialNumber",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("serial_number", models.CharField(max_length=255, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "batch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="serial_numbers",
                        to="inventory.batch",
                    ),
                ),
            ],
            options={
                "verbose_name": "Serial Number",
                "verbose_name_plural": "Serial Numbers",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["batch"], name="inventory_s_batch_i_8c7681_idx"
                    )
                ],
            },
        ),
    ]
