# Generated by Django 5.2.17 on 2026-08-31 23:08

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("business", "0003_business_brand_fields"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BusinessCurrencyConfig",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("currency_code", models.CharField(default="IDR", max_length=3)),
                ("currency_symbol", models.CharField(default="Rp", max_length=5)),
                (
                    "decimal_places",
                    models.IntegerField(
                        default=0,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(4),
                        ],
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "business",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="currency_config",
                        to="business.business",
                    ),
                ),
            ],
            options={
                "verbose_name": "Business Currency Config",
                "verbose_name_plural": "Business Currency Configs",
            },
        ),
        migrations.CreateModel(
            name="BusinessIntegrationConfig",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "webhook_url",
                    models.URLField(
                        blank=True, default=None, max_length=500, null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "business",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="integration_config",
                        to="business.business",
                    ),
                ),
            ],
            options={
                "verbose_name": "Business Integration Config",
                "verbose_name_plural": "Business Integration Configs",
            },
        ),
        migrations.CreateModel(
            name="BusinessInvoiceConfig",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("invoice_prefix", models.CharField(default="INV-", max_length=20)),
                (
                    "invoice_next_number",
                    models.IntegerField(
                        default=1,
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                ("invoice_notes", models.TextField(blank=True, default="")),
                ("invoice_footer", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "business",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="invoice_config",
                        to="business.business",
                    ),
                ),
            ],
            options={
                "verbose_name": "Business Invoice Config",
                "verbose_name_plural": "Business Invoice Configs",
            },
        ),
        migrations.CreateModel(
            name="BusinessReceiptConfig",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("receipt_prefix", models.CharField(default="RCT-", max_length=20)),
                (
                    "receipt_next_number",
                    models.IntegerField(
                        default=1,
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                ("receipt_notes", models.TextField(blank=True, default="")),
                ("receipt_footer", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "business",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="receipt_config",
                        to="business.business",
                    ),
                ),
            ],
            options={
                "verbose_name": "Business Receipt Config",
                "verbose_name_plural": "Business Receipt Configs",
            },
        ),
        migrations.CreateModel(
            name="BusinessTaxConfig",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "tax_rate",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                ("tax_name", models.CharField(default="PPN", max_length=50)),
                ("tax_inclusive", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "business",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tax_config",
                        to="business.business",
                    ),
                ),
            ],
            options={
                "verbose_name": "Business Tax Config",
                "verbose_name_plural": "Business Tax Configs",
            },
        ),
        migrations.CreateModel(
            name="UserNotificationPreference",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("receive_stock_alerts", models.BooleanField(default=True)),
                ("receive_order_alerts", models.BooleanField(default=True)),
                ("receive_payment_alerts", models.BooleanField(default=True)),
                ("receive_subscription_alerts", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "business",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_notification_preferences",
                        to="business.business",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notification_preferences",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "User Notification Preference",
                "verbose_name_plural": "User Notification Preferences",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user", "business"),
                        name="unique_user_business_notification_preference",
                    )
                ],
            },
        ),
    ]
