# Generated by Django 5.2.17 on 2026-08-22 18:09

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("business", "0004_businessmembership"),
        ("customer", "0001_initial"),
        ("product", "0002_variant_create"),
        ("sales", "0002_sale_customer_sale_loyalty_earned_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Cart",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("session_token", models.CharField(max_length=255, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "customer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="carts",
                        to="customer.customer",
                    ),
                ),
            ],
            options={
                "verbose_name": "Cart",
                "verbose_name_plural": "Carts",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="CartItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.DecimalField(decimal_places=2, max_digits=12)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "cart",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="onlinestore.cart",
                    ),
                ),
                (
                    "variant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cart_items",
                        to="product.variant",
                    ),
                ),
            ],
            options={
                "verbose_name": "CartItem",
                "verbose_name_plural": "CartItems",
            },
        ),
        migrations.CreateModel(
            name="OnlineOrder",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("CONFIRMED", "Confirmed"),
                            ("COMPLETED", "Completed"),
                            ("CANCELED", "Canceled"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("guest_name", models.CharField(max_length=255)),
                ("guest_email", models.EmailField(blank=True, max_length=254)),
                ("guest_phone", models.CharField(blank=True, max_length=50)),
                ("shipping_address", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "customer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="orders",
                        to="customer.customer",
                    ),
                ),
                (
                    "sale",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="online_orders",
                        to="sales.sale",
                    ),
                ),
            ],
            options={
                "verbose_name": "OnlineOrder",
                "verbose_name_plural": "OnlineOrders",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="OnlineOrderLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.DecimalField(decimal_places=2, max_digits=12)),
                ("unit_price", models.DecimalField(decimal_places=2, max_digits=12)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "online_order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lines",
                        to="onlinestore.onlineorder",
                    ),
                ),
                (
                    "variant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="order_lines",
                        to="product.variant",
                    ),
                ),
            ],
            options={
                "verbose_name": "OnlineOrderLine",
                "verbose_name_plural": "OnlineOrderLines",
            },
        ),
        migrations.CreateModel(
            name="OnlineStore",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("slug", models.SlugField(max_length=255, unique=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "business",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="online_stores",
                        to="business.business",
                    ),
                ),
                (
                    "default_location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="online_store_default",
                        to="business.location",
                    ),
                ),
            ],
            options={
                "verbose_name": "OnlineStore",
                "verbose_name_plural": "OnlineStores",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="onlineorder",
            name="online_store",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="orders",
                to="onlinestore.onlinestore",
            ),
        ),
        migrations.AddField(
            model_name="cart",
            name="online_store",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="carts",
                to="onlinestore.onlinestore",
            ),
        ),
        migrations.CreateModel(
            name="OnlineStoreProduct",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_published", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "online_store",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="published_products",
                        to="onlinestore.onlinestore",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="online_store_publishings",
                        to="product.product",
                    ),
                ),
            ],
            options={
                "verbose_name": "OnlineStoreProduct",
                "verbose_name_plural": "OnlineStoreProducts",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="onlinestore",
            index=models.Index(
                fields=["business"], name="onlinestore_busines_b3c19b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="onlinestore",
            index=models.Index(fields=["slug"], name="onlinestore_slug_544af5_idx"),
        ),
        migrations.AddIndex(
            model_name="onlineorder",
            index=models.Index(
                fields=["online_store"], name="onlinestore_online__a0f211_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="onlineorder",
            index=models.Index(fields=["status"], name="onlinestore_status_ac9fb1_idx"),
        ),
        migrations.AddConstraint(
            model_name="onlinestoreproduct",
            constraint=models.UniqueConstraint(
                fields=("online_store", "product"), name="unique_online_store_product"
            ),
        ),
    ]
